productcompare/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('scrapper.urls',namespace='scrapper'))
]

scrapper/urls.py
from django.urls import path
from .views import HomeView, SearchView , DetailView

app_name = "scrapper"
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('search/<str:product_name>/', SearchView.as_view(), name='search'),
    path('Detail/<int:id>/', DetailView.as_view(), name='detail')
]

scrapper/models.py
from django.db import models


class Product(models.Model):

    name=models.CharField(max_length=300)
    title=models.CharField(max_length=300)
    price=models.CharField(max_length=300)
    rating=models.CharField(max_length=300)
    image_url=models.URLField(max_length=300)
    url=models.URLField(max_length=300)
    website=models.CharField(max_length=300)

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)

# Create your models here.

scrapper/views.py
from django.shortcuts import render, redirect
from django.views import View
from .scrapper import FlipkartScrapper, Scrapper
from .models import *

class HomeView(View):

    template_name = 'homepage.html'

    def get(self, request):
        Product.objects.all().delete()
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        search = request.POST.get('search')
        print(search)

        return redirect('scrapper:search', product_name=search)


class SearchView(View):

    template_name = 'products.html'

    def get(self, request, product_name):

        scrap = Scrapper()
        links = scrap.get_links(product_name)

        amazon_object_list = scrap.get_object_list(links)
        
        f_scrap = FlipkartScrapper()
        flip_links = f_scrap.get_links(product_name)
        flipkart_object_list = f_scrap.get_object_list(flip_links)


        object_list = amazon_object_list + flipkart_object_list
        # request.session['object_list']
        for object in object_list:
            product = Product(name=product_name,title=object.title,price=object.price, rating=object.star,image_url=object.image_url,url=object.url,website=object.website)
            product.save()
            for review in object.reviews_list:
                r = Review(product=product, text=review)
                r.save()
        object_list = Product.objects.filter(name=product_name)
        context = {
            'product_name': product_name,
            'object_list': object_list
        }
        return render(request, self.template_name, context)


class DetailView(View):

    template_name = 'reviews.html'

    def get(self, request, id, *args, **kwargs):

        object = Product.objects.get(id=id)
        review_list = object.review_set.all()
        
        context = {
            'object':object,
            'review_list':review_list
            
            }

        return render(request, self.template_name, context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Online Comparer</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
        crossorigin="anonymous">



    {% block custom_css %}{% endblock custom_css %}

</head>

<body>
    {% include 'includes/navbar.html' %}

    {% block content %}

    {% endblock content %}


    <!-- All javascript files goes under here    -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}




<div class="container">
	<div class="row justify-content-center">

	<form action="" method="POST">



		{% csrf_token %}
        <div class="container">
    <div class="row">
        <div class="col">
            <div id="home-content">
                <h1>Product Compare</h1>

                <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img src="{% static 'css/static/img/img2.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="{% static 'css/static/img/img1.png' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="{% static 'css/static/img/img3.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                  </div>
                </div>
                <h3>Search the name of the product!</h3>
                <br>
                <div class="input-group mb-3">

                  <button type="submit" class="btn btn-primary">Search</button>

                        <input type="text" name="search" class="form-control" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                </div>
            </div>
        </div>
    </div>
</div>



	</form>
</div></div>






{% endblock content %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href=""><i class="fas fa-book-reader"></i></a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'scrapper:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>

        </ul>

        </div>
    </div>
</nav>

templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <!-- <div class="row justify-content-center">
    <h1>
        Product:{{product_name}}
    </h1>
  </div>

    {% for object in object_list %}

    <div class="card">
  <div class="card-header">
    {{object.title}}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{object.price}}</h5>
    <p class="card-text">{{object.star}}</p>
    <p class="card-text">{{object.website}}</p>
    <p class="card-text">{{object.image_url}}</p>
    <a href="{{object.url}}" class="btn btn-primary">Visit</a>
      <hr>
      <ul class="list-group">
          Reviews:
       {% for object in object.reviews_list %}

  <li class="list-group-item">{{forloop.counter}}){{object}}</li>
        <hr>
          <hr>

       {% endfor %}
           </ul>
  </div>
</div>
    <hr>
    <br>
    <hr>

    {%  endfor %} -->


    <!-- {% for object in object_list %}
    {% if forloop.counter0|divisibleby:3 %} <div class="row"> {%  endif %}
        <div class="col-md-4">
       <div class="card text-dark bg-light" style="width: 18rem;">
      <img src="{{object.image_url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{object.title}}</h5>
        <p class="card-text"></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{{object.price}}</li>
        <li class="list-group-item">{{object.star}}</li>
    <li class="list-group-item">{{object.website}}</li>
      </ul>
           
      <div class="card-body">
        <a href="{{object.url}}" class="card-link">Visit</a>
        <a href="" class="card-link">Reviews</a>
      </div>
    </div>
        </div>
    {%  if forloop.counter|divisibleby:3 or forloop.last %}</div><br>{%  endif %}
    {%  endfor %}
    </div> -->

    <div class="container">
      <div class="row justify-content-center">
        <h1>{{product_name}}</h1>
      </div>
    </div>

    {% for object in object_list %}
    {% if forloop.counter0|divisibleby:1 %} <div class="row"> {%  endif %}
      <div class="col d-flex justify-content-center"> 
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="w-100">
          <img src="{{object.image_url}}" alt="...">
        </div>
        <div class="w-100">
          <div class="card-body align-items-center">
            <h5 class="card-title">{{object.title}}</h5>
            <p class="card-text">{{object.price}}</p>
            <p class="card-text">{{object.star}}</p>
            <a href="{{object.url}}" class="btn btn-dark">Visit</a>
            <a href="{% url 'scrapper:detail' object.id %}" class="btn btn-dark">Reviews</a>
            <p class="card-text"><small class="text-muted">{{object.website}}</small></p>
          </div>
        </div>
      </div>
    </div>
  </div>
    {%  if forloop.counter|divisibleby:1 or forloop.last %}</div><br>{%  endif %}
    {% endfor %}

</div>

{% endblock %}

templates/reviews.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <h1>
        Product:{{product_name}}
    </h1>
  </div>
</div>



<div class="card text-center">

  <div class="card-body">
      <div class="row justify-content-center">
        <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
            
            <li class="list-group-item"><b></b> {{ object.title}}</li>
            <li class="list-group-item"><b>Price:</b> {{ object.price }}</li>
            <li class="list-group-item"><b>Rating:</b>{{ object.rating }}</li>

        <li class="list-group-item">
            <a href="{{object.url}}" class="btn btn-danger">
                Visit</a>
        </li>
      </ul>
     
    </div>
      </div>
      <ul class="list-group">
        Reviews:
     {% for object in review_list %}

<li class="list-group-item">{{forloop.counter}}){{object.text}}</li>
      <hr>
        

     {% endfor %}
         </ul>
  </div>

</div>



{% endblock %}